apiVersion: v1
kind: Secret
metadata:
  name: git-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  username: Z3VhcmRpYW4=
  password: Z2hwX3NVUk5FOVRGUWZOZE5vM1JSMTVnY21ualJjMlBlMDNKUUVQZg==