---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: voltran
  namespace: argo-cd
spec:
  description: Voltran Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'